# Generated by Django 6.0.3 on 2026-04-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenancealert',
            new_name='alerts_main_machine_e87bd4_idx',
            old_name='alerts_main_machine_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenancealert',
            new_name='alerts_main_status_12c8d7_idx',
            old_name='alerts_main_status_idx',
        ),
    ]
