# Generated by Django 6.0.3 on 2026-04-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenancereport',
            new_name='reports_mai_machine_85247c_idx',
            old_name='reports_main_machine_idx',
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
