# Generated by Django 6.0.3 on 2026-04-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='machines_se_machine_ff0370_idx',
            old_name='machines_se_machine_idx',
        ),
    ]
